services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ./frontend/
    env_file:
      - .env
    volumes:
      - static:/app/build/

  gateway:
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - static:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media: